### ISSUE TITLE
Recent PinePhone Pro fix needed after I2S fix

### ISSUE THREAD

**Issue by ghost** [Biktorgj/meta-qcom#17]
Hi there!

Looking at the recent change for the PinePhone Pro, the codec gets restarted before the call is started. This, as mentioned adds latency waiting for the codec to start up again. The issue with the audio codec on the PinePhone Pro appears to lie with the I2S_CKR register getting reset after a suspend, https://gitlab.com/mobian1/devices/rockchip-linux/-/issues/5 .

Just wondering when this patch comes in to fix the register issue/weird audio after suspend , would this recent commit even be necessary? 

Thanks.

**Comment by ghost** [comment]
For reference: 23f56a1244a32fee13a34eeafb8caaa0f211009d

**Comment by Biktorgj** [comment]
Hi!
This is a workaround I hope to be able to remove when everything is working fine with audio in the Pro, but it's not directly related to the pitched-up audio issue.

The Pinephone Pro shows two issues with audio:
- When suspending, if the rockchip_i2s driver has suspended before going to sleep, shutting down a clock, when it comes back on on resume with the issue. That can be worked around in various ways:
  - Not disabling the clock before suspend
  - Setting up an invalid clock rate prior to suspend, so the kernel readjusts it on resume
  - Force-changing the rate twice when we're going to start a stream
Note all these are just workarounds, as far as I know no one has found exactly _why_ it happens.

- Sometimes, when you receive an incoming call in the Pinephone Pro while it is suspended, the modem's kernel will log errors when trying to communicate via i2c with the _modem's_ audio codec. This seems to happen because power is cut off from the the audio codec on suspend, and the modem tries to set it up before power has been restored to it. This commit just works around this issue, while I investigate if I can do something about it from the [modem's] kernel itself.

In any case, this specific issue seems more power related than anything. Another option could be to prevent the codecs from powering down, but I tried and didn't succeed at that, and all distros are doing it anyway, so I better make something that works for everyone (even if it wastes a few miliseconds), that force all users to patch their kernels :)

**Comment by ghost** [comment]
Ohhhh good idea sorry that is me being silly haha. Thank you for explaining!! 

Good idea to do something here rather than get distros to patch and reship their kernels, thank you again. :))
